<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net11.0;net10.0;net9.0;net8.0</TargetFrameworks>
  </PropertyGroup>

  <Import Project="..\..\..\..\shared.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="$(MicrosoftAzureCosmosVersion)" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="$(MicrosoftSqlClientVersion)" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="$(MatchTargetFrameworkVersion)" />
    <PackageReference Include="MongoDB.Driver" Version="$(MongoDbDriverVersion)" />
    <PackageReference Include="MySql.Data" Version="$(MySqlDataVersion)" />
    <PackageReference Include="MySqlConnector" Version="$(MySqlConnectorVersion)" />
    <PackageReference Include="Newtonsoft.Json" Version="$(NewtonsoftJsonVersion)" />
    <PackageReference Include="Npgsql" Version="$(EntityFrameworkCorePossiblyDowngradedTestVersion)" />
    <PackageReference Include="RabbitMQ.Client" Version="$(RabbitClientTestVersion)" />
    <PackageReference Include="System.Data.SqlClient" Version="$(SystemSqlClientVersion)" />
    <PackageReference Include="System.Text.Json" Version="$(FoundationalVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Connectors\Steeltoe.Connectors.csproj" />
  </ItemGroup>
</Project>
