<Project>
  <PropertyGroup>
    <!--
      Non-exposed dependencies, only referenced from test projects, build infrastructure and internal tools.
      It's safe to update these at any time, so wildcards are allowed anywhere.
    -->

    <AspNetCoreHealthChecksVersion>9.0.*</AspNetCoreHealthChecksVersion>
    <CoverletVersion>10.0.*</CoverletVersion>
    <FluentAssertionsVersion>7.2.*</FluentAssertionsVersion>
    <MicrosoftAzureCosmosVersion>3.62.*</MicrosoftAzureCosmosVersion>
    <MicrosoftBuildUtilitiesCoreVersion>18.9.*</MicrosoftBuildUtilitiesCoreVersion>
    <MicrosoftCodeAnalysisVersion>5.9.*</MicrosoftCodeAnalysisVersion>
    <MicrosoftSqlClientVersion>7.0.*</MicrosoftSqlClientVersion>
    <MockHttpVersion>7.1.*</MockHttpVersion>
    <MongoDbDriverVersion>3.11.*</MongoDbDriverVersion>
    <MySqlConnectorVersion>2.6.*</MySqlConnectorVersion>
    <MySqlDataVersion>26.7.*</MySqlDataVersion>
    <NewtonsoftJsonVersion>13.0.*</NewtonsoftJsonVersion>
    <NSubstituteVersion>6.2.*</NSubstituteVersion>
    <PublicApiAnalyzersVersion>5.6.*</PublicApiAnalyzersVersion>
    <RabbitClientTestVersion>7.2.*</RabbitClientTestVersion>
    <SerilogEnrichersThreadVersion>4.0.*</SerilogEnrichersThreadVersion>
    <SerilogExceptionsVersion>8.4.*</SerilogExceptionsVersion>
    <SonarAnalyzerVersion>10.33.0.1635</SonarAnalyzerVersion>
    <StyleCopVersion>1.2.0-beta.556</StyleCopVersion>
    <SystemCommandLineVersion>2.0.*</SystemCommandLineVersion>
    <SystemIdentityModelVersion>8.22.*</SystemIdentityModelVersion>
    <SystemSqlClientVersion>4.9.*</SystemSqlClientVersion>
    <TestSdkVersion>18.9.*</TestSdkVersion>
    <TimeProviderTestingVersion>10.9.*</TimeProviderTestingVersion>
    <XunitVersion>3.2.*</XunitVersion>
    <XunitVisualStudioVersion>4.0.*</XunitVisualStudioVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <EntityFrameworkCorePossiblyDowngradedTestVersion>10.0.*</EntityFrameworkCorePossiblyDowngradedTestVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net11.0'">
    <EntityFrameworkCorePossiblyDowngradedTestVersion>10.0.*</EntityFrameworkCorePossiblyDowngradedTestVersion>
  </PropertyGroup>

  <PropertyGroup>
    <!--
      Exposed dependencies, observable by Steeltoe library consumers.
      Be cautious with updates:
      - Wildcards are only allowed at the patch level, so we automatically benefit from vulnerability fixes.
      - Major/minor versions here generally should not change between minor/patch versions of Steeltoe.
    -->

    <BouncyCastleVersion>2.2.*</BouncyCastleVersion>
    <ConsulVersion>1.8.*</ConsulVersion>
    <DotnetGCDumpVersion>9.0.652701</DotnetGCDumpVersion>
    <FoundationalVersion>
      <!--
        Package versions of this category are always safe to update to the latest version, because they multi-target all frameworks.
        For example, v10 explicitly targets .NET 10; v11 explicitly targets .NET 10 and 11.
      -->
      10.0.*
    </FoundationalVersion>
    <MicrosoftDiagnosticsNETCoreClientVersion>0.2.652701</MicrosoftDiagnosticsNETCoreClientVersion>
    <MicrosoftDiagnosticsTracingTraceEventVersion>3.1.23</MicrosoftDiagnosticsTracingTraceEventVersion>
    <OpenTelemetryExporterPrometheusVersion>1.15.*-*</OpenTelemetryExporterPrometheusVersion>
    <OpenTelemetryVersion>1.15.*</OpenTelemetryVersion>
    <SerilogExtensionsLoggingVersion>10.0.*</SerilogExtensionsLoggingVersion>
    <SerilogSettingsConfigurationVersion>10.0.*</SerilogSettingsConfigurationVersion>
    <SerilogSinksConsoleVersion>6.1.*</SerilogSinksConsoleVersion>
    <SerilogVersion>9.0.*</SerilogVersion>
    <SystemTextJsonVersion>11.0.*-*</SystemTextJsonVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <EntityFrameworkCoreVersion>10.0.*</EntityFrameworkCoreVersion>
    <MatchTargetFrameworkVersion>
      <!--
        Package versions of this category are bound to the target framework, so they cannot be updated to the latest version.
        For example, v10 targets only .NET 10; v11 targets only .NET 11.
        Caution: some packages additionally target netstandard, but result in compile-time/runtime errors or reduced API surface.
      -->
      10.0.*
    </MatchTargetFrameworkVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net11.0'">
    <EntityFrameworkCoreVersion>11.0.*-*</EntityFrameworkCoreVersion>
    <MatchTargetFrameworkVersion>
      <!--
        Package versions of this category are bound to the target framework, so they cannot be updated to the latest version.
        For example, v10 targets only .NET 10; v11 targets only .NET 11.
        Caution: some packages additionally target netstandard, but result in compile-time/runtime errors or reduced API surface.
      -->
      11.0.*-*
    </MatchTargetFrameworkVersion>
  </PropertyGroup>
</Project>
