//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steeltoe.Bootstrap.Autoconfig {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steeltoe.Bootstrap.Autoconfig.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured actuators.
        /// </summary>
        internal static string WireAllActuators {
            get {
                return ResourceManager.GetString("WireAllActuators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Cloud Foundry actuators.
        /// </summary>
        internal static string WireCloudFoundryActuators {
            get {
                return ResourceManager.GetString("WireCloudFoundryActuators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Cloud Foundry configuration provider.
        /// </summary>
        internal static string WireCloudFoundryConfiguration {
            get {
                return ResourceManager.GetString("WireCloudFoundryConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Cloud Foundry MTLs security.
        /// </summary>
        internal static string WireCloudFoundryContainerIdentity {
            get {
                return ResourceManager.GetString("WireCloudFoundryContainerIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured config server configuration provider.
        /// </summary>
        internal static string WireConfigServer {
            get {
                return ResourceManager.GetString("WireConfigServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured ConnectionStrings configuration provider.
        /// </summary>
        internal static string WireConnectorsConfiguration {
            get {
                return ResourceManager.GetString("WireConnectorsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured discovery client.
        /// </summary>
        internal static string WireDiscoveryClient {
            get {
                return ResourceManager.GetString("WireDiscoveryClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Redis distributed cache connector.
        /// </summary>
        internal static string WireDistributedRedisCache {
            get {
                return ResourceManager.GetString("WireDistributedRedisCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured distributed tracing.
        /// </summary>
        internal static string WireDistributedTracing {
            get {
                return ResourceManager.GetString("WireDistributedTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured dynamic console logger.
        /// </summary>
        internal static string WireDynamicLogging {
            get {
                return ResourceManager.GetString("WireDynamicLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured dynamic console logger for Serilog.
        /// </summary>
        internal static string WireDynamicSerilog {
            get {
                return ResourceManager.GetString("WireDynamicSerilog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Kubernetes actuators.
        /// </summary>
        internal static string WireKubernetesActuators {
            get {
                return ResourceManager.GetString("WireKubernetesActuators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Kubernetes configuration provider.
        /// </summary>
        internal static string WireKubernetesConfiguration {
            get {
                return ResourceManager.GetString("WireKubernetesConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured MongoDB connector.
        /// </summary>
        internal static string WireMongoClient {
            get {
                return ResourceManager.GetString("WireMongoClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured MySQL connector.
        /// </summary>
        internal static string WireMySqlConnection {
            get {
                return ResourceManager.GetString("WireMySqlConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Oracle connector.
        /// </summary>
        internal static string WireOracleConnection {
            get {
                return ResourceManager.GetString("WireOracleConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured placeholder configuration provider.
        /// </summary>
        internal static string WirePlaceholderResolver {
            get {
                return ResourceManager.GetString("WirePlaceholderResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured PostgreSQL connector.
        /// </summary>
        internal static string WirePostgresConnection {
            get {
                return ResourceManager.GetString("WirePostgresConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured RabbitMQ connector.
        /// </summary>
        internal static string WireRabbitMqConnection {
            get {
                return ResourceManager.GetString("WireRabbitMqConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Random Value configuration provider.
        /// </summary>
        internal static string WireRandomValueProvider {
            get {
                return ResourceManager.GetString("WireRandomValueProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured StackExchange RabbitMQ connector.
        /// </summary>
        internal static string WireRedisConnectionMultiplexer {
            get {
                return ResourceManager.GetString("WireRedisConnectionMultiplexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured SQL Server connector.
        /// </summary>
        internal static string WireSqlServerConnection {
            get {
                return ResourceManager.GetString("WireSqlServerConnection", resourceCulture);
            }
        }
    }
}
