// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Steeltoe.Bootstrap.AutoConfiguration")]
[assembly: InternalsVisibleTo("Steeltoe.Bootstrap.AutoConfiguration.Test")]
[assembly: InternalsVisibleTo("Steeltoe.Common.Certificates")]
[assembly: InternalsVisibleTo("Steeltoe.Common.Certificates.Test")]
[assembly: InternalsVisibleTo("Steeltoe.Common.Hosting")]
[assembly: InternalsVisibleTo("Steeltoe.Common.Hosting.Test")]
[assembly: InternalsVisibleTo("Steeltoe.Common.Http")]
[assembly: InternalsVisibleTo("Steeltoe.Common.Test")]
[assembly: InternalsVisibleTo("Steeltoe.Configuration.CloudFoundry")]
[assembly: InternalsVisibleTo("Steeltoe.Configuration.CloudFoundry.Test")]
[assembly: InternalsVisibleTo("Steeltoe.Configuration.ConfigServer")]
[assembly: InternalsVisibleTo("Steeltoe.Configuration.Encryption")]
[assembly: InternalsVisibleTo("Steeltoe.Configuration.Kubernetes.ServiceBindings")]
[assembly: InternalsVisibleTo("Steeltoe.Configuration.Placeholder")]
[assembly: InternalsVisibleTo("Steeltoe.Connectors")]
[assembly: InternalsVisibleTo("Steeltoe.Connectors.EntityFrameworkCore")]
[assembly: InternalsVisibleTo("Steeltoe.Discovery.Configuration")]
[assembly: InternalsVisibleTo("Steeltoe.Discovery.Configuration.Test")]
[assembly: InternalsVisibleTo("Steeltoe.Discovery.Consul")]
[assembly: InternalsVisibleTo("Steeltoe.Discovery.Consul.Test")]
[assembly: InternalsVisibleTo("Steeltoe.Discovery.Eureka")]
[assembly: InternalsVisibleTo("Steeltoe.Discovery.Eureka.Test")]
[assembly: InternalsVisibleTo("Steeltoe.Discovery.HttpClients")]
[assembly: InternalsVisibleTo("Steeltoe.Discovery.HttpClients.Test")]
[assembly: InternalsVisibleTo("Steeltoe.Logging.Abstractions")]
[assembly: InternalsVisibleTo("Steeltoe.Logging.DynamicLogger")]
[assembly: InternalsVisibleTo("Steeltoe.Logging.DynamicSerilog")]
[assembly: InternalsVisibleTo("Steeltoe.Management.Abstractions")]
[assembly: InternalsVisibleTo("Steeltoe.Management.Endpoint")]
[assembly: InternalsVisibleTo("Steeltoe.Management.Endpoint.Test")]
[assembly: InternalsVisibleTo("Steeltoe.Management.Prometheus")]
[assembly: InternalsVisibleTo("Steeltoe.Management.Tasks")]
[assembly: InternalsVisibleTo("Steeltoe.Management.Tracing")]
[assembly: InternalsVisibleTo("Steeltoe.Management.Tracing.Test")]
[assembly: InternalsVisibleTo("Steeltoe.Security.Authentication.CloudFoundry.Test")]
[assembly: InternalsVisibleTo("Steeltoe.Security.Authorization.Certificate")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
