<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net11.0;net10.0</TargetFrameworks>
    <Description>Manage minimum logging levels at runtime using Serilog.</Description>
    <PackageTags>logging;dynamic-logging;serilog;log-management;monitoring</PackageTags>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <Import Project="..\..\..\..\shared.props" />

  <ItemGroup>
    <PackageReference Include="Serilog.Extensions.Logging" Version="$(SerilogExtensionsLoggingVersion)" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="$(SerilogSettingsConfigurationVersion)" />
    <PackageReference Include="Serilog.Sinks.Console" Version="$(SerilogSinksConsoleVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abstractions\Steeltoe.Logging.Abstractions.csproj" />
  </ItemGroup>
</Project>
