// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.ActuatorServiceCollectionExtensions.AddAllActuators(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration,Steeltoe.Management.Endpoint.MediaTypeVersion,System.Action{Microsoft.AspNetCore.Cors.Infrastructure.CorsPolicyBuilder})~Microsoft.Extensions.DependencyInjection.IServiceCollection")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.ManagementHostBuilderExtensions.ActivateActuatorEndpoints(Microsoft.Extensions.DependencyInjection.IServiceCollection,System.Action{Microsoft.AspNetCore.Builder.IEndpointConventionBuilder})")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.ManagementWebApplicationBuilderExtensions.AddCommonServices(Microsoft.AspNetCore.Builder.WebApplicationBuilder)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.ManagementWebHostBuilderExtensions.GetManagementUrl(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Nullable{System.Int32}@,System.Nullable{System.Int32}@)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Metrics.EndpointServiceCollectionExtensions.AddMetricsActuator(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Metrics.MetricsEndpoint.#ctor(Steeltoe.Management.Endpoint.Metrics.IMetricsEndpointOptions,Steeltoe.Management.MetricCollectors.Exporters.Steeltoe.SteeltoeExporter,Microsoft.Extensions.Logging.ILogger{Steeltoe.Management.Endpoint.Metrics.MetricsEndpoint})")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Metrics.Observer.AspNetCoreHostingObserver.#ctor(Steeltoe.Management.Endpoint.Metrics.IMetricsObserverOptions,Microsoft.Extensions.Logging.ILogger{Steeltoe.Management.Endpoint.Metrics.Observer.AspNetCoreHostingObserver})")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Metrics.Observer.HttpClientCoreObserver.#ctor(Steeltoe.Management.Endpoint.Metrics.IMetricsObserverOptions,Microsoft.Extensions.Logging.ILogger{Steeltoe.Management.Endpoint.Metrics.Observer.HttpClientCoreObserver})")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Metrics.Observer.HttpClientDesktopObserver.#ctor(Steeltoe.Management.Endpoint.Metrics.IMetricsObserverOptions,Microsoft.Extensions.Logging.ILogger{Steeltoe.Management.Endpoint.Metrics.Observer.HttpClientDesktopObserver})")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.ActuatorServiceCollectionExtensions.AddAllActuators(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration,Steeltoe.Management.Endpoint.MediaTypeVersion,System.Action{Microsoft.AspNetCore.Cors.Infrastructure.CorsPolicyBuilder})~Microsoft.Extensions.DependencyInjection.IServiceCollection")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.ManagementWebHostBuilderExtensions.GetManagementUrl(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Nullable{System.Int32}@,System.Nullable{System.Int32}@)")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Metrics.EndpointServiceCollectionExtensions.AddMetricsActuator(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Metrics.MetricsEndpoint.#ctor(Steeltoe.Management.Endpoint.Metrics.IMetricsEndpointOptions,Steeltoe.Management.MetricCollectors.Exporters.Steeltoe.SteeltoeExporter,Microsoft.Extensions.Logging.ILogger{Steeltoe.Management.Endpoint.Metrics.MetricsEndpoint})")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Metrics.MetricsEndpoint.GetMetricSamplesByTags(Steeltoe.Management.MetricCollectors.MetricsCollection{System.Collections.Generic.List{Steeltoe.Management.MetricCollectors.MetricSample}},System.String,System.Collections.Generic.IEnumerable{System.Collections.Generic.KeyValuePair{System.String,System.String}})~System.Collections.Generic.List{Steeltoe.Management.MetricCollectors.MetricSample}")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Metrics.Observer.HttpClientCoreObserver.#ctor(Steeltoe.Management.Endpoint.Metrics.IMetricsObserverOptions,Microsoft.Extensions.Logging.ILogger{Steeltoe.Management.Endpoint.Metrics.Observer.HttpClientCoreObserver})")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Metrics.Observer.HttpClientDesktopObserver.#ctor(Steeltoe.Management.Endpoint.Metrics.IMetricsObserverOptions,Microsoft.Extensions.Logging.ILogger{Steeltoe.Management.Endpoint.Metrics.Observer.HttpClientDesktopObserver})")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.ManagementWebHostBuilderExtensions.GetManagementUrl(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Nullable{System.Int32}@,System.Nullable{System.Int32}@)")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Metrics.MetricsEndpoint.GetMetricSamplesByTags(Steeltoe.Management.MetricCollectors.MetricsCollection{System.Collections.Generic.List{Steeltoe.Management.MetricCollectors.MetricSample}},System.String,System.Collections.Generic.IEnumerable{System.Collections.Generic.KeyValuePair{System.String,System.String}})~System.Collections.Generic.List{Steeltoe.Management.MetricCollectors.MetricSample}")]
