<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net11.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <Import Project="..\..\..\..\shared.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(EntityFrameworkCoreVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EntityFrameworkCoreVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(EntityFrameworkCoreVersion)" />
    <PackageReference Include="Microting.EntityFrameworkCore.MySql" Version="$(EntityFrameworkCorePossiblyDowngradedTestVersion)" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="$(EntityFrameworkCorePossiblyDowngradedTestVersion)" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="$(EntityFrameworkCoreVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Management\src\Tasks\Steeltoe.Management.Tasks.csproj" />
    <ProjectReference Include="..\..\src\EntityFrameworkCore\Steeltoe.Connectors.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
