name: Steeltoe.Connectors

on:
  workflow_dispatch: {}
  pull_request:
    paths:
    - .editorconfig
    - stylecop.json
    - '*.props'
    - '*.ruleset'
    - .config/dotnet-tools.json
    - .github/workflows/component-shared-workflow.yml
    - .github/workflows/component-connectors.yml
    - src/Connectors/**
    - src/Steeltoe.Connectors.slnf

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    uses: ./.github/workflows/component-shared-workflow.yml
    with:
      component: Connectors
      OS: ubuntu
