name: Steeltoe.Configuration

on:
  workflow_dispatch: {}
  pull_request:
    paths:
    - .editorconfig
    - stylecop.json
    - '*.props'
    - '*.ruleset'
    - .config/dotnet-tools.json
    - .github/workflows/component-shared-workflow.yml
    - .github/workflows/component-configuration.yml
    - src/Configuration/**
    - src/Steeltoe.Configuration.slnf

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    uses: ./.github/workflows/component-shared-workflow.yml
    with:
      component: Configuration
      OS: ubuntu
      runConfigServer: true
