name: Scan vulnerable dependencies

on:
  workflow_dispatch:
  push:
    branches:
    - '3.x'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: true
  SOLUTION_FILE: 'src/Steeltoe.All.sln'

jobs:
  scan:
    name: Scan
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          6.0.*
          8.0.*
          10.0.*

    - name: Git checkout
      uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Report vulnerable dependencies
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $PSNativeCommandUseErrorActionPreference = $true

        $output = dotnet list ${{ env.SOLUTION_FILE }} package --vulnerable --include-transitive --format json --output-version 1 2>&1
        $text = ($output | Out-String).TrimEnd()
        $json = $text | ConvertFrom-Json

        foreach ($project in $json.projects) {
          if ($project.frameworks) {
            Write-Host 'Vulnerable package references were found.'
            dotnet list ${{ env.SOLUTION_FILE }} package --vulnerable --include-transitive
            exit 1
          }
        }
