name: Verify code style

on:
  push:
    branches: [ 'main', 'release/*' ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: true

jobs:
  verify-code-style:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.*
          9.0.*

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Restore tools
      run: dotnet tool restore --verbosity minimal

    - name: Restore packages
      run: dotnet restore src --verbosity minimal

    - name: Set package version
      run: nbgv cloud

    - name: CleanupCode (on PR diff)
      if: github.event_name == 'pull_request'
      shell: pwsh
      run: |
        # Not using the environment variables for SHAs, because they may be outdated. This may happen on force-push after the build is queued, but before it starts.
        # The below works because HEAD is detached (at the merge commit), so HEAD~1 is at the base branch. When a PR contains no commits, this job will not run.
        $headCommitHash = git rev-parse HEAD
        $baseCommitHash = git rev-parse HEAD~1

        Write-Output "Running code cleanup on commit range $baseCommitHash..$headCommitHash in pull request."
        dotnet regitlint -s src/Steeltoe.All.sln --print-command --skip-tool-check --max-runs=5 --jb --dotnetcoresdk=$(dotnet --version) --jb-profile="Steeltoe Full Cleanup" --jb --properties:Configuration=Release --jb --properties:RunAnalyzers=false --jb --properties:NuGetAudit=false --jb --verbosity=WARN -f commits -a $headCommitHash -b $baseCommitHash --fail-on-diff --print-diff

    - name: CleanupCode (on branch)
      if: github.event_name == 'push' || github.event_name == 'release'
      shell: pwsh
      run: |
        Write-Output "Running code cleanup on all files."
        dotnet regitlint -s JsonApiDotNetCore.sln --print-command --skip-tool-check --jb --dotnetcoresdk=$(dotnet --version) --jb-profile="Steeltoe Full Cleanup" --jb --properties:Configuration=Release --jb --properties:RunAnalyzers=false --jb --properties:NuGetAudit=false --jb --verbosity=WARN --fail-on-diff --print-diff
