// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Test.BaseTest.GetTestMetrics(Steeltoe.Management.MetricCollectors.Exporters.Steeltoe.SteeltoeExporter)~System.Diagnostics.Metrics.AggregationManager")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Test.BaseTest.GetTestMetrics(Steeltoe.Management.MetricCollectors.Exporters.Steeltoe.SteeltoeExporter)~System.Diagnostics.Metrics.AggregationManager")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Test.Metrics.AspNetCoreHostingObserverTest.GetException_ReturnsExpected")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Test.Metrics.AspNetCoreHostingObserverTest.GetException_ReturnsExpected")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Test.Metrics.AspNetCoreHostingObserverTest.GetLabelSets_ReturnsExpected")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Test.Metrics.AspNetCoreHostingObserverTest.GetLabelSets_ReturnsExpected")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Test.Metrics.AspNetCoreHostingObserverTest.ShouldIgnore_ReturnsExpected")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Test.Metrics.EndpointServiceCollectionExtensionsTest.GetConfiguration~Microsoft.Extensions.Configuration.IConfiguration")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "member", Target = "~M:Steeltoe.Management.Endpoint.Test.Metrics.EndpointServiceCollectionExtensionsTest.GetConfiguration~Microsoft.Extensions.Configuration.IConfiguration")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "Working on it", Scope = "type", Target = "~T:Steeltoe.Management.Endpoint.Test.Metrics.ServiceCollectionTests")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Working on it", Scope = "type", Target = "~T:Steeltoe.Management.Endpoint.Test.Metrics.ServiceCollectionTests")]
